name: Actualizar Loterias
on:
  workflow_dispatch: 
  schedule:
    - cron: '30 21 * * *'

permissions:
  contents: write # Esto soluciona el error 128 (Permiso de escritura)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4 # Versión moderna
      - name: Configurar Python
        uses: actions/setup-python@v5 # Versión moderna
        with:
          python-version: '3.11' # Versión estable de Python
      - name: Instalar librerias
        run: pip install requests
      - name: Ejecutar extractor
        run: python extractor.py
      - name: Guardar cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bonoloto.json
          git commit -m "Actualizacion automatica de resultados" || exit 0
          git push
