name: Actualizar Loterias
on:
  workflow_dispatch: 
  schedule:
    - cron: '30 21 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar librerias
        run: pip install requests
      - name: Ejecutar extractor
        run: python extractor.py
      - name: Guardar cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Esto le da la "llave" maestra
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add bonoloto.json
          git commit -m "Actualizacion automatica de resultados" || exit 0
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
